### DISCUSSION TITLE
代码高亮插件显示效果，左上角的三个仿mac的红绿黄实心圆能不能去掉或者有选项可以隐藏

### DISCUSSION THREAD

**Discussion by zhousy29** [solstice23/argon-theme#356] [Ideas]
在暗黑主题下，这三个圆好刺眼啊

**Comment by solstice23** [comment]
```css
pre.hljs-codeblock:before {
    display: none;
}
code[hljs-codeblock-inner] {
    padding-top: 22px;
}
```
