### ISSUE TITLE
手机/平板 safari 浏览器点击“赞赏”按钮无法弹出图片二维码

### ISSUE THREAD

**Issue by crowya** [solstice23/argon-theme#23]
手机/平板 **safari 浏览器** 上存在的一些问题：
1.点击赞赏按钮无法弹出图片二维码；
2.左侧栏搜索框无法呼出输入法键盘。

其他改进建议：
1.个人感觉“回到顶部”的图标太细小了，建议放大或加粗或更换图标。
FA方向类图标：https://www.runoob.com/font-awesome/fontawesome-icons-directional.html
推荐 fa fa-arrow-up 或 fa fa-chevron-up 。
2.希望能有设置阴影默认为深阴影、字体默认为宋体的选项。

**Comment by crowya** [comment]
新问题：文章过时信息显示那里如果更新时间很近会变成-1天或者0天。建议小于或等于0直接显示为今天，1天前直接显示为昨天。

**Comment by solstice23** [comment]
> 手机/平板 safari 浏览器 上存在的一些问题：
> 1.点击赞赏按钮无法弹出图片二维码；
> 2.左侧栏搜索框无法呼出输入法键盘。

暂时没有 IOS 设备，无法调试，有可能是 `width: max-content` 的问题，新版本尝试修复，**可能**可以解决。

> 个人感觉“回到顶部”的图标太细小了，建议放大或加粗或更换图标。

现在图标还可以的，如果觉得细，可以添加这段 CSS 来变粗。
```css
#fabtn_back_to_top i:before {
    content: "\f077";
    display: block;
    transform: translateY(-2px);
    font-size: 10px;
}
```

> 2.希望能有设置阴影默认为深阴影、字体默认为宋体的选项。

稍后更新。

> 文章过时信息显示那里如果更新时间很近会变成-1天或者0天。建议小于或等于0直接显示为今天，1天前直接显示为昨天。

时差的 BUG 已修复，稍后更新。显示为今天/昨天好像没有必要，当天更新的文章不能算作过时。
