### ISSUE TITLE
字体大小

### ISSUE THREAD

**Issue by WangLiwen1994** [solstice23/argon-theme#247]
感谢大佬制作分享主题。请问可不可以增加一个设置选项，可以调整文字的大小。 我用的是英文版，感觉菜单文字有点小。

**Comment by solstice23** [comment]
可以用 CSS 覆盖默认字体大小

**Comment by huangwb8** [comment]
@WangLiwen1994 

我最近刚好也想调大字体，和某大佬讨论了一下，自己测试可行。这里也贴出我的方案供后来者参考！

进入WordPress后台，在`外观——自定义——额外css`中加入以下内容：

```css
/*更改默认字体大小*/
/*文章标题*/
.post-title {
  font-size: 30px
}
/*正文内容（不包含代码）*/
.post-content p{
  font-size: 1.2rem;
}
li{
  font-size: 1.2rem;
}
/*尾注*/
.additional-content-after-post{
  font-size: 1.2rem
}
```
自己可以微调上面的数字以达到满意的效果。

我的博文还介绍了很多WordPress相关的特效，感兴趣的话自己去看吧！地址是：[Docker系列 WordPress系列 特效](https://blognas.hwb0307.com/linux/docker/744)。
