### ISSUE TITLE
Making theme more customizable?

### ISSUE THREAD

**Issue by nyanpasu64** [solstice23/argon-theme#260]
It would be nice to have more options to customize/simplify the theme's appearance:

Make floating header bar not float. (Currently, `#leftbar_part2` gets pinned at `top: 40px` when the page scrolls down. You'd have to change the JS breakpoint where the bar moves from regular positioning to fixed, and change the CSS to reduce the `top` value.)

```css
.headroom--pinned, .headroom--unpinned {
	position: absolute !important;
}
```

Make the banner a fixed-height bar, rather than expanding vertically on taller windows.

```css
.banner {
	height: unset;
}
.banner > .banner-container {
	height: unset !important;
}
.banner > .banner-container > .banner-title {
	position: unset;
	top: unset;
	transform: unset;
}
#content {
	margin-top: unset;
}
```

Turn off `#leftbar_part2` from being generated in the source. Currently I send it to viewers' computers but hide it with CSS, which is inefficient:

```css
#leftbar_part2 {
	display: none;
}
```

**Comment by nyanpasu64** [comment]
Hide banner text, eliminate banner entirely except as a background for the navbar (in a hacky way), and make the navbar title bigger:

```css
.banner {
	height: calc(3.75rem + 2px); /* this is a hack sadly */
	padding: 0;
}
.banner > .banner-container {
	display: none !important;
}
/* why does .navbar-brand have 2 different font sizes in the source code? */
.navbar-brand {
	font-size: 20px;
	font-weight: 400;
}
```

Hide the leftbar entirely (also wasteful in HTML):

```
#content {
	max-width: 900px;
}
#content > #leftbar {
	display: none;
}
#content > #primary {
	width: unset;
	float: none;
}
```
