### ISSUE TITLE
FontAwesome升级到6.0的建议

### ISSUE THREAD

**Issue by Jiaocz** [solstice23/argon-theme#401]
最近FontAwesome升级了6.0免费版，其中增加了Icon动画、新图标等。

作为一个提议，是否可以将主题的FontAwesome从`4.17`升级到`6.0.0`？

一个建议就是，先提供平滑过渡，然后将4.0的`fa fa-icon`写法设置成`deprecated`，在某个特定版本之后移除（或者根本就并存不移除）。

<details open>
<summary><b>平滑过渡建议</b></summary>
<p>因为<a href="https://cdn.staticfile.org/font-awesome/6.0.0/css/all.css" target="_blank">FA 6的css</a>写的适配性很强，因此只需要<b>在CSS引入FA的CSS</b>，然后在CSS中加入：</p>
<pre>
--fa-style-family: FontAwesome;
</pre>
<p>就可以强制<code>.fa</code>选择器的icon强制使用FA 4的字体，以保证适配FA 4</p>
<p>对于FA 6，官方的写法为<code>fas</code>或<code>fa-solid</code>等写法，不会与FA 4冲突</p>
</details>

---

**示例**

我的博客的修改在[这个CSS](https://blog.orangii.cn/wp-content/themes/argon-orange/style.css)

```css
@import url('https://cdn.staticfile.org/font-awesome/6.0.0/css/all.min.css');

:root {
	--fa-style-family: FontAwesome;
}
```
目前可以到[我的博客](https://blog.orangii.cn)去看一下效果，本来自带的4版本仍然可以用，也可以使用开发者工具尝试修改为FA 6图标，也可以正常使用。

如果需要的话之后可以提交pr帮修改现存的图标和添加新的依赖。
