### ISSUE TITLE
夜间模式下文字颜色需要与 gruber-markdown 插件进行适配

### ISSUE THREAD

**Issue by lushuyu** [solstice23/argon-theme#42]
![image](https://user-images.githubusercontent.com/27007632/83329566-d471ca80-a2bc-11ea-9e35-c6c452dd862d.png)

gruber-markdown 字体颜色并没有跟随夜间模式变化，所以需要在 css 上做出一些小改动。

**Comment by solstice23** [comment]
字体黑色的原因是 `gruber-markdown` 插件的 CSS 覆盖了 Argon 夜间模式下字体颜色的 CSS

解决方法：
添加如下 CSS 到 "自定义页面 CSS" 中：
```css
html.darkmode .gruber-markdown p{
    color: #eee;
}
```
