### ISSUE TITLE
[BUG] 图片无法居中，始终居左

### ISSUE THREAD

**Issue by Liyccccc** [solstice23/argon-theme#464]
WordPress: 5.9.3
Argon: 1.3.5，且启用了Fancybox图片放大浏览

编辑文章时，使用”添加媒体“插入一张本地图片，插入时对齐方式选择居中，自动产生的HTML代码大概如下：

``` html
<img src="image_url" alt="" width="xxx" height="xxx" class="aligncenter size-full wp-image-431" />
```

在经典可视化编辑器中图片可以居中显示，但最终实际效果依然为居左显示。

**Comment by icecliffs** [comment]
一个快速解决方法，自定义CSS。贴入

```css
.fancybox-wrapper{
	margin: 0 auto;
}
.fancybox-wrapper img{
	padding: 10px;
	border-radius: 6px;
	box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px;
	transition: 0.2s ease;
}
```
